{{- if .Values.django.ingress.enabled -}}
{{- $fullName := include "defectdojo.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    defectdojo.org/component: django
    app.kubernetes.io/name: {{ include "defectdojo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "defectdojo.chart" . }}
spec:
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
  {{- if .Values.django.ingress.ingressClassName }}
  ingressClassName: {{ .Values.django.ingress.ingressClassName }}
  {{- end }}
{{- end }}
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
        - pathType: Prefix
          {{- if .Values.django.ingress.path }}
          path: {{ .Values.django.ingress.path }}
          {{- else }}
          path: "/"
          {{- end }}
          backend:
            service:
              name: {{ $fullName }}-django
              port:
                name: http
{{- end }}
